export const mapEventType = {
  change: "change",
  "change:layerGroup": "change:layerGroup",
  "change:size": "change:size",
  "change:target": "change:target",
  "change:view": "change:view",
  click: "click",
  dblclick: "dblclick",
  error: "error",
  loadend: "loadend",
  loadstart: "loadstart",
  moveend: "moveend",
  movestart: "movestart",
  pointerdrag: "pointerdrag",
  pointermove: "pointermove",
  postcompose: "postcompose",
  postrender: "postrender",
  precompose: "precompose",
  propertychange: "propertychange",
  rendercomplete: "rendercomplete",
  singleclick: "singleclick",
};
